DROP TABLE IF EXISTS accounts;
CREATE TABLE ACCOUNTS (CUSTOMER_NUMBER VARCHAR(8), ACCOUNT_NUMBER VARCHAR(12), PRODUCT_NUMBER VARCHAR(3),PRODUCT_NAME VARCHAR(20), STATUS VARCHAR(3), BALANCE DECIMAL(15, 2), CREATION_DATE VARCHAR(10));

DROP TABLE IF EXISTS cards;
CREATE TABLE CARDS (
    ACCOUNT_NUMBER VARCHAR(12),
    CARD_NUMBER VARCHAR(16),
    CARD_TYPE VARCHAR(1),
    STATUS VARCHAR(3),
    CREATION_DATE VARCHAR(10)
);
