
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, NAME, LAST_NAME, SESION, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000001', 'John', 'Lopez', false, 'password', 'johnlopcas@gmail.com', 'A', '2022-01-11');
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, NAME, LAST_NAME, SESION, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000002', 'Jhosua', 'Lopez', false, 'pass', 'jhosua.lopez@gmail.com', 'B', '2022-01-11');
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, NAME, LAST_NAME, SESION, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000003', 'Jony', 'Lopez', false, 'password', 'johnlopcas@gmail.com', 'A', '2022-01-11');
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, NAME, LAST_NAME, SESION, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000004', 'Oscar', 'Perez', false, 'pass2', 'oscar@gmail.com', 'A', '2022-01-11');